# Build stage
FROM node:20 as build-stage

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy rest of your frontend code
COPY . .

# Build the Vue.js app for production
RUN npm run build

# Production stage (nginx)
FROM nginx:stable-alpine as production-stage

# Copy built files to nginx public folder
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
